name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sync
        uses: patrickwyler/gcs-bucket-sync-action@1.4
        with:
          secrets: ${{ secrets.google_service_account_credentials }}
          bucket: 'wm-fuse-bucket'
          exclude: '.*\.md$|\.gitignore$|\.git/.*$|\.github/.*$'
  
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
      - name: Collect Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          json: "true"
          include_all_old_new_renamed_files: "true"
      - name: Debug Changed Files Outputs
        run: |
          echo "Added files: ${{ steps.changed-files.outputs.added_files }}"
          echo "Copied files: ${{ steps.changed-files.outputs.copied_files }}"
          echo "Modified files: ${{ steps.changed-files.outputs.modified_files }}"
          echo "Renamed files: ${{ steps.changed-files.outputs.renamed_files }}"
          echo "Deleted files: ${{ steps.changed-files.outputs.deleted_files }}"   
          echo " old rename: ${{ steps.changed-files.outputs.all_old_new_renamed_files }}"

        shell: bash
      - name: Create JSON File with Changed Files
        run: |
          # Get the outputs and ensure they are in JSON format
          added='${{ steps.changed-files.outputs.added_files }}'
          copied='${{ steps.changed-files.outputs.copied_files }}'
          modified='${{ steps.changed-files.outputs.modified_files }}'
          renamed='${{ steps.changed-files.outputs.all_old_new_renamed_files }}'
          deleted='${{ steps.changed-files.outputs.deleted_files }}'
          echo "$modified"
          echo "******* $deleted"
          # Construct the new JSON object
          #jq -n --arg added "$modified" '{"modified": $added}'

          new_json=$(jq -n \
            --arg added "$added" \
            --arg copied "$copied" \
            --arg modified "$modified" \
            --arg renamed "$renamed" \
            --arg deleted "$deleted" \
            '{
              "added": $added,
              "copied": $copied,
              "modified": $modified,
              "renamed": $renamed,
              "deleted": $deleted
            }')
        
          # Write the JSON object to the file
          echo "$new_json" > changed_files.json
        
          # Print the contents of the JSON file
          cat changed_files.json

        shell: bash
