name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sync
        uses: patrickwyler/gcs-bucket-sync-action@1.4
        with:
          secrets: ${{ secrets.google_service_account_credentials }}
          bucket: 'wm-fuse-bucket'
          exclude: '.*\.md$|\.gitignore$|\.git/.*$|\.github/.*$'
  
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: changed-files
      - run: |
          echo "Added files: ${{ steps.changed-files.outputs.added_files }}"
          echo "Modified files: ${{ steps.changed-files.outputs.modified_files }}"
          echo "Deleted files: ${{ steps.changed-files.outputs.deleted_files }}"
          echo "Copied files: ${{ steps.changed-files.outputs.copied_files }}"
          echo "Renamed files: ${{ steps.changed-files.outputs.renamed_files }}"
          
      # - uses: yumemi-inc/changed-files@v3
      #   id: changed
      #   with:
      #     format: 'json'
      #     statuses: 'added|modified|renamed'
      # - run: |
      #     for file in ${{ steps.changed.outputs.files }}; do
      #       echo "$file"
      #     done
      
      # - name: Get changed files
      #   id: changed-files
      #   uses: tj-actions/changed-files@v44
      #   with:
      #     json: "true"
      #   # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
      #   # with:
      #   #   since_last_remote_commit: true 

      # - name: List all changed files
      #   env:
      #     ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_modified_files }}
      #   run: |
      #     for file in ${ALL_CHANGED_FILES}; do
      #       echo "$file was changed"
      #     done
